### ISSUE TITLE
Unable to select servers, no rich presence created.

### ISSUE THREAD

**Issue by TheCatMan2000** [Arno500/plex-richpresence#9]
```
2022/03/06 08:15:05 Detected language: en
2022/03/06 08:15:05 Refreshing servers
2022/03/06 08:15:05 We never had an access token, generating it
2022/03/06 08:15:05 We never had a pin on Plex, creating one
2022/03/06 08:15:05 The client identifier has never been set. Generating one.
2022/03/06 08:15:07 Waiting for user authentication
2022/03/06 08:15:12 Server A: Trying to connect to 172[obfuscated]dab7.plex.direct:32400
2022/03/06 08:15:12 Server B: Trying to connect to 192[obfuscated]bc20.plex.direct:32400
2022/03/06 08:15:13 Server A: 172[obfuscated]dab7.plex.direct:32400 was successfully contacted
2022/03/06 08:15:13 Server B: Trying to connect to 47[obfuscated]bc20.plex.direct:[redacted]
2022/03/06 08:15:13 Server B: 47[obfuscated]bc20.plex.direct:17541 was successfully contacted
2022/03/06 08:15:13 Sucessfully connected to https://172[obfuscated]dab7.plex.direct:32400 WebSocket
2022/03/06 08:15:13 Sucessfully connected to https://47[obfuscated]bc20.plex.direct:[redacted] WebSocket
2022/03/06 08:15:18 Couldn't connect or lost connection to Server B
2022/03/06 08:15:19 Couldn't connect or lost connection to Server A
2022/03/06 08:15:19 Couldn't connect or lost connection to Server B
2022/03/06 08:15:20 Couldn't connect or lost connection to Server A
...repeats 3 times...
2022/03/06 08:15:22 Couldn't connect or lost connection to Server B
2022/03/06 08:15:23 Couldn't connect or lost connection to Server B
2022/03/06 08:15:24 Added new device  (, )
2022/03/06 08:16:13 Refreshing servers
...repeats 3 times...
```
Server A is local and Server B is remote.
Playing media on either of them doesn't create any "Playing..." status on discord.

Server select menu just appears like this:
![image](https://user-images.githubusercontent.com/27119164/156927394-2146c8c3-bce4-4ba7-a905-52e2322c37cb.png)

Config looks looks like this:
```json
{
	"timeMode": "elapsed",
	"clientId": "[redacted]",
	"accessToken": "[redacted]",
	"pin": {
		"id": 123456789,
		"code": "[redacted]"
	},
	"enableNewDevicesByDefault": true,
	"selectedDevices": [
		{
			"name": "",
			"enabled": true,
			"product": "",
			"title": ""
		}
	]
}
```

**Comment by Arno500** [comment]
Hello @TheCatMan2000 !
I have a few questions about your env:
- Are you a Plex pass subscriber? I did not do a lot of testing for this (but I guess it should still work even if you're not)
- Are you using an account that is the owner of the servers? (not so much testing neither…)
- Are you connected to the remote one using a relay? I'd guess not, since the domain ends in .direct
- Do you have a special proxy/VPN/tunneling/reverse-proxy setup? All the cases I tested were with a direct connection.

Other than that,I struggle a bit to find why the connection is dropping after a few seconds...
I included a special version here ([plex-rich-presence_windows_amd64-dev.zip](https://github.com/Arno500/plex-richpresence/files/8193884/plex-rich-presence_windows_amd64-dev.zip)) that you can test that logs the error of the disconnect (and is a future release, too ;) ). Can you run it and send your new logs if you see something new?
Thanks again !

**Comment by TheCatMan2000** [comment]
- Yes, I am a Plex Pass subscriber.
- Yes, My account is the owner of these servers.
- No, Server B has remote access set up properly with a port open on the network that machine is on. Server A doesn't work through the proxy for some reason, so I'm using it directly over my local network.
- I don't think I was using a VPN at the time. I do have one set up to manage Server B, but I'm unsure if I had it on at the time of getting those logs.

Here's the logs with that special version you sent. I got a similar result doing this with and without the VPN. Something else I've noticed is the selectedDevices array in the config file has no entries rather than what I had before.
```
...
2022/03/06 19:21:09 Sucessfully connected to https://172[obfuscated]dab7.plex.direct:[redacted] WebSocket
2022/03/06 19:21:09 Sucessfully connected to https://47[obfuscated]bc20.plex.direct:[redacted] WebSocket
2022/03/06 19:22:09 Refreshing servers
2022/03/06 19:22:49 Couldn't connect or lost connection to Server A
2022/03/06 19:22:49 json: cannot unmarshal string into Go struct field Setting.NotificationContainer.Setting.value of type int64
2022/03/06 19:22:50 Couldn't connect or lost connection to Server A
2022/03/06 19:22:50 json: cannot unmarshal bool into Go struct field Setting.NotificationContainer.Setting.default of type string
2022/03/06 19:22:50 Couldn't connect or lost connection to Server B
2022/03/06 19:22:50 json: cannot unmarshal string into Go struct field Setting.NotificationContainer.Setting.value of type int64
2022/03/06 19:22:50 Couldn't connect or lost connection to Server A
2022/03/06 19:22:50 json: cannot unmarshal number into Go struct field Setting.NotificationContainer.Setting.default of type string
2022/03/06 19:22:50 Couldn't connect or lost connection to Server A
2022/03/06 19:22:50 json: cannot unmarshal string into Go struct field Setting.NotificationContainer.Setting.value of type int64
2022/03/06 19:22:51 Couldn't connect or lost connection to Server B
2022/03/06 19:22:51 json: cannot unmarshal bool into Go struct field Setting.NotificationContainer.Setting.default of type string
2022/03/06 19:22:51 Couldn't connect or lost connection to Server A
2022/03/06 19:22:51 json: cannot unmarshal number into Go struct field Setting.NotificationContainer.Setting.default of type string
2022/03/06 19:22:52 Couldn't connect or lost connection to Server B
2022/03/06 19:22:52 json: cannot unmarshal bool into Go struct field Setting.NotificationContainer.Setting.default of type string
2022/03/06 19:23:10 Refreshing servers
...repeats 5 times...
```
```json
	"selectedDevices": []
```

**Comment by Arno500** [comment]
Alright, I know why it happens. I don't know why I don't get these myself, though. I will create another build ASAP that SHOULD resolve the issue :)

**Comment by Arno500** [comment]
Can you try this build, please? It should contain the fix related to the two unmarshall errors you encountered, which were causing the disconnect :)
[plex-rich-presence_windows_amd64-dev.zip](https://github.com/Arno500/plex-richpresence/files/8210735/plex-rich-presence_windows_amd64-dev.zip)
Thanks again!

**Comment by R3D4CTED** [comment]
Same here on macOS. I cloned the latest version of master and compiled from source and ended up with no rich presence showing. Devices section is blank. I'm not a Plex Pass subscriber and don't own the server I'm streaming from.

**Comment by Arno500** [comment]
@R3D4CTED I just pushed the fixes to master (it was only on my machine before), so you may try cloning, updating the deps with `go get` and rebuild.
(on the side, it's great news the app is working as intended on macOS, it was not a given especially for the GUI part!)

**Comment by R3D4CTED** [comment]
> @R3D4CTED I just pushed the fixes to master (it was only on my machine before), so you may try cloning, updating the deps with `go get` and rebuild. (on the side, it's great news the app is working as intended on macOS, it was not a given especially for the GUI part!)

No such luck, ending up with the same error, and nothing shows up under the "Devices" tab. As for GUI, do you mean the tray? Because that's all the GUI I'm seeing.
Logs:
```
2022/03/09 17:35:22 Cannot set language automatically (Could not detect Language), setting to english
2022/03/09 17:35:22 Checking for updates...
2022/03/09 17:35:22 Error while checking for updates:  Malformed version:
2022/03/09 17:35:22 Refreshing servers
2022/03/09 17:35:22 We never had an access token, generating it
2022/03/09 17:35:22 We never had a pin on Plex, creating one
2022/03/09 17:35:22 The client identifier has never been set. Generating one.
2022/03/09 17:35:23 Waiting for user authentication
2022/03/09 17:35:25 Waiting for user authentication
2022/03/09 17:35:28 Waiting for user authentication
2022/03/09 17:35:31 REDACTED: Trying to connect to redacted:443
2022/03/09 17:35:31 REDACTED1 - REDACTED1: Trying to connect to redacted1:443
2022/03/09 17:35:31 REDACTED - REDACTED: redacted:443 was successfully contacted
2022/03/09 17:35:31 REDACTED: redacted:443 was successfully contacted
2022/03/09 17:35:31 Sucessfully connected to https://redacted1:443 WebSocket
2022/03/09 17:35:31 Sucessfully connected to https://redacted:443 WebSocket
2022/03/09 17:36:31 Refreshing servers
2022/03/09 17:37:32 Refreshing servers
2022/03/09 17:38:33 Refreshing servers
2022/03/09 17:39:35 Refreshing servers
```
And I've attached a screenshot to show you the tray icon
<img width="490" alt="Screenshot 2022-03-09 at 5 43 05 PM" src="https://user-images.githubusercontent.com/28143681/157439945-52b479a5-230e-421b-bccd-652c7014fbd7.png">

Clicking on the devices section also does nothing.

**Comment by TheCatMan2000** [comment]
I'm seeing similar behavior that @R3D4CTED described on Windows.
![B5VNtQ6Ru4](https://user-images.githubusercontent.com/27119164/158093343-4642cf65-c262-41bc-95e3-53b7279a21c1.gif)


> Can you try this build, please? It should contain the fix related to the two unmarshall errors you encountered, which were causing the disconnect :) [plex-rich-presence_windows_amd64-dev.zip](https://github.com/Arno500/plex-richpresence/files/8210735/plex-rich-presence_windows_amd64-dev.zip) Thanks again!

It also seems that unmarshal error is still appearing.
```
2022/03/13 21:22:29 Detected language: en
2022/03/13 21:22:29 Checking for updates...
2022/03/13 21:22:29 Refreshing servers
2022/03/13 21:22:29 We never had an access token, generating it
2022/03/13 21:22:29 We never had a pin on Plex, creating one
2022/03/13 21:22:29 The client identifier has never been set. Generating one.
2022/03/13 21:22:31 Waiting for user authentication
2022/03/13 21:22:33 Waiting for user authentication
2022/03/13 21:22:39 Server A: Trying to connect to 172[obfuscated]dab7.plex.direct:[redacted]
2022/03/13 21:22:39 Server B: Trying to connect to 192[obfuscated]bc20.plex.direct:[redacted]
2022/03/13 21:22:39 Server A: 172[obfuscated]dab7.plex.direct:32400 was successfully contacted
2022/03/13 21:22:39 Server B: Trying to connect to 47[obfuscated]bc20.plex.direct:[redacted]
2022/03/13 21:22:39 Server B: 47[obfuscated]bc20.plex.direct:[redacted] was successfully contacted
2022/03/13 21:22:39 Sucessfully connected to https://172[obfuscated]dab7.plex.direct:[redacted] WebSocket
2022/03/13 21:22:39 Sucessfully connected to https://47[obfuscated]bc20.plex.direct:[redacted] WebSocket
2022/03/13 21:22:41 Couldn't connect or lost connection to Server A
2022/03/13 21:22:41 json: cannot unmarshal number into Go struct field Setting.NotificationContainer.Setting.default of type bool
2022/03/13 21:23:39 Refreshing servers
2022/03/13 21:24:41 Refreshing servers
```

**Comment by Arno500** [comment]
Will look into that at the end of the week (I hope)...
Thanks for the logs, anyway!

**Comment by Arno500** [comment]
I found the issue: basically, when the server sends a state notification, it does not include device information such as the platform or the name of the device, which means it never gets added to the list.
Unfortunately, for non-admins users, I don't see any positive outcome currently, and I'll have to bypass the device selection feature :/
I'm trying to sniff the incoming JSON to find whether I can find interesting things or find another API call that can fulfill the need, but I'm not sure…

**Comment by Arno500** [comment]
@TheCatMan2000 and @R3D4CTED 
Can you try with this shiny new release: https://github.com/Arno500/plex-richpresence/releases/tag/1.5.0
It should now work and correctly detect devices for "non-owner" users :)
Sorry for the long delay, I've been busy with other projects :)

**Comment by cobrabr** [comment]
Interestingly, this only started happening lately for me. 1.5.0 was working fine, but with 1.5.2 (which I can't find as its own release, but it was auto-updated) the problem described by the OP is happening to me as well.

**Comment by SerenModz21** [comment]
> I'm seeing similar behavior that @R3D4CTED described on Windows. ![B5VNtQ6Ru4](https://user-images.githubusercontent.com/27119164/158093343-4642cf65-c262-41bc-95e3-53b7279a21c1.gif) [ ![B5VNtQ6Ru4](https://user-images.githubusercontent.com/27119164/158093343-4642cf65-c262-41bc-95e3-53b7279a21c1.gif) ](https://user-images.githubusercontent.com/27119164/158093343-4642cf65-c262-41bc-95e3-53b7279a21c1.gif) [ ](https://user-images.githubusercontent.com/27119164/158093343-4642cf65-c262-41bc-95e3-53b7279a21c1.gif)
> 
> > Can you try this build, please? It should contain the fix related to the two unmarshall errors you encountered, which were causing the disconnect :) [plex-rich-presence_windows_amd64-dev.zip](https://github.com/Arno500/plex-richpresence/files/8210735/plex-rich-presence_windows_amd64-dev.zip) Thanks again!
> 
> It also seems that unmarshal error is still appearing.
> 
> ```
> 2022/03/13 21:22:29 Detected language: en
> 2022/03/13 21:22:29 Checking for updates...
> 2022/03/13 21:22:29 Refreshing servers
> 2022/03/13 21:22:29 We never had an access token, generating it
> 2022/03/13 21:22:29 We never had a pin on Plex, creating one
> 2022/03/13 21:22:29 The client identifier has never been set. Generating one.
> 2022/03/13 21:22:31 Waiting for user authentication
> 2022/03/13 21:22:33 Waiting for user authentication
> 2022/03/13 21:22:39 Server A: Trying to connect to 172[obfuscated]dab7.plex.direct:[redacted]
> 2022/03/13 21:22:39 Server B: Trying to connect to 192[obfuscated]bc20.plex.direct:[redacted]
> 2022/03/13 21:22:39 Server A: 172[obfuscated]dab7.plex.direct:32400 was successfully contacted
> 2022/03/13 21:22:39 Server B: Trying to connect to 47[obfuscated]bc20.plex.direct:[redacted]
> 2022/03/13 21:22:39 Server B: 47[obfuscated]bc20.plex.direct:[redacted] was successfully contacted
> 2022/03/13 21:22:39 Sucessfully connected to https://172[obfuscated]dab7.plex.direct:[redacted] WebSocket
> 2022/03/13 21:22:39 Sucessfully connected to https://47[obfuscated]bc20.plex.direct:[redacted] WebSocket
> 2022/03/13 21:22:41 Couldn't connect or lost connection to Server A
> 2022/03/13 21:22:41 json: cannot unmarshal number into Go struct field Setting.NotificationContainer.Setting.default of type bool
> 2022/03/13 21:23:39 Refreshing servers
> 2022/03/13 21:24:41 Refreshing servers
> ```

im having this issue with 1.6.2
![image](https://cdn.serenmodz.rocks/CZfdIbZ.png)

```
2022/12/07 04:50:52 Detected language: en
2022/12/07 04:50:52 Checking for updates...
2022/12/07 04:50:53 [AutoUpdater] Local Version 1.6.2 - Remote Version: 1.6.2
2022/12/07 04:50:53 Refreshing servers
2022/12/07 04:50:53 [redacted]: Trying to connect to [redacted].6e050d813bbe400b812009994a372bee.plex.direct:32400
2022/12/07 04:50:54 [redacted]: Trying to connect to [redacted].6e050d813bbe400b812009994a372bee.plex.direct:32400
2022/12/07 04:50:55 [redacted]: Trying to connect to [redacted].6e050d813bbe400b812009994a372bee.plex.direct:32400
2022/12/07 04:50:55 [redacted]: [redacted].6e050d813bbe400b812009994a372bee.plex.direct:32400 was successfully contacted
2022/12/07 04:50:55 Sucessfully connected to https://[redacted].6e050d813bbe400b812009994a372bee.plex.direct:32400 WebSocket
2022/12/07 04:51:55 Refreshing servers
2022/12/07 04:52:56 Refreshing servers
2022/12/07 04:53:56 Refreshing servers
2022/12/07 04:54:58 Refreshing servers
2022/12/07 04:55:59 Refreshing servers
2022/12/07 04:57:00 Refreshing servers
```

**Comment by d2freak** [comment]
I'm getting the exact same issue with 1.7.0. Same log messages and no devices list via the tray icon.

I have access to 3 servers. I own one of the servers, 2 other servers are just shared. I've tried running the tool as admin and not. It signs in correctly to Plex. I have Plex pass. Nothing works.

The only thing I can think of is that is unorthodox is that I'm running AdGuard on this computer. It tunnels traffic through itself but it doesn't cause issues with anything else. Plex Relay is not involved.

**Comment by Arno500** [comment]
Sorry for the silence on this issue, I was pretty busy lately, but this is going on my todo to make the app usable for more people :)
See you soon, when I can work on that :p (possibly next week? Worst case, next month)

**Comment by Arno500** [comment]
@SerenModz21 and @d2freak,
Did you try playing some content first? Plex RP doesn't scan for devices (to prevent automatically adding hundred of old devices) beforehand, and simply add them when they start playing content. So you can try to play something somewhere and then the device should automatically be added to the list.

**Comment by d2freak** [comment]
@Arno500 Yes, I did. That's when I noticed there wasn't anything being published to discord. I tried playing music in PlexAmp mostly but I also tried playing videos in a few clients. The log does not move when I do this and no client appears.

My plays are visible in the Plex dashboard.

**Comment by Arno500** [comment]
@d2freak a few questions on the top of my mind
- Are you admin of the server where you're playing content from?
- Is your server on your local network
- Is it exposed to the internet? (with port forwarding)
- Do you have Plex Relay enabled?

And finally, can you add the version of Plex Media Server you are using? (found in Settings > General)

I'm really lost on your case, I don't see any particular element, it seems that it is connecting correctly, but just not detecting any play which is incredibly weird.

**Comment by d2freak** [comment]
1. Yes, but I tried other servers too.
2. Yes.
3. Yes.
4. Enabled yes. In use no.
5. 1.32.5.7328 (latest public)

I don't think I'm running anything particular that is out the ordinary. Worth noting is that I tried another program to publish Plex playing on Discord and that worked fine (although I'd much rather use this).

**Comment by SerenModz21** [comment]
> @SerenModz21 and @d2freak, Did you try playing some content first? Plex RP doesn't scan for devices (to prevent automatically adding hundred of old devices) beforehand, and simply add them when they start playing content. So you can try to play something somewhere and then the device should automatically be added to the list.

It has been a couple of months but no, I don't think I did. I originally thought it would just scan automatically because there is no mention of this in the readme. Therefore, I think you should clearly state this using GitHub's note/warning markdown (https://github.com/orgs/community/discussions/16925) otherwise new users will get the same idea.

I will give it another try, considering what you said and see what its like from there.

**Comment by SerenModz21** [comment]
I am media playing right now and the program has refreshed several times but the devices list remain empty, with no RPC showing on Discord. I am playing media on my own Plex server, therefore, I have admin to the server. I am connected to my server remotely therefore it is exposed to the internet. I also have Plex Relay enabled, however, I am direct playing said media and not making use of the relay. Finally, my server is running Plex Media Server 1.32.5.7328 just like [d2freak](https://github.com/d2freak).

Here is the logs:
```
2023/07/23 20:20:21 Checking for updates...
2023/07/23 20:20:21 [AutoUpdater] Local Version 1.7.0 - Remote Version: 1.7.0
2023/07/23 20:20:21 Refreshing servers
2023/07/23 20:20:21 We never had an access token, generating it
2023/07/23 20:20:21 We never had a pin on Plex, creating one
2023/07/23 20:20:21 The client identifier has never been set. Generating one.
2023/07/23 20:20:22 Waiting for user authentication
2023/07/23 20:20:27 ServerName: Trying to connect to XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400
2023/07/23 20:20:27 ServerName: Trying to connect to XX-XX-XXX-XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400
2023/07/23 20:20:27 ServerName: XX-XX-XXX-XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400 was successfully contacted
2023/07/23 20:21:27 Refreshing servers
2023/07/23 20:22:28 Refreshing servers
2023/07/23 20:23:28 Refreshing servers
2023/07/23 20:24:29 Refreshing servers
2023/07/23 20:25:29 Refreshing servers
2023/07/23 20:26:30 Refreshing servers
2023/07/23 20:27:30 Refreshing servers
2023/07/23 20:28:31 Refreshing servers
2023/07/23 20:29:31 Refreshing servers
2023/07/23 20:30:32 Refreshing servers
2023/07/23 20:31:32 Refreshing servers
```

**Comment by Arno500** [comment]
Hello @SerenModz21 and @d2freak,
I pushed a new update that should fix your issues. You can try https://github.com/Arno500/plex-richpresence/releases/tag/1.8.0.
It should automatically update on the next start of the program.
Thanks a lot @d2freak for your extensive testing, and @SerenModz21 for your logs!
I'll close this issue, now :)
(feel free to comment if it still doesn't work)

**Comment by SerenModz21** [comment]
Thank you @Arno500! I can confirm that 1.8.0 has indeed resolved the issue. Much appreciated for the work you have done with the RPC.
